backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# npx decap-server to start the local server
# http://localhost:5173/admin/index.html to test locally
# uncomment the local_backend section to use the local server

# local_backend:
#   url: http://localhost:8081/api/v1

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "products"
    label: "Products"
    folder: "src/assets/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Price", name: "price", widget: "number" }
      - { label: "Description", name: "description", widget: "text" }
      
  - name: "testimonials_data"
    label: "Testimonials"
    delete: false
    editor:
      preview: false
    files:
      - name: "testimonials"
        label: "Testimonials"
        file: "src/data/testimonials.json"
        fields:
          - name: "testimonials"
            label: "Testimonials"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Text", name: "text", widget: "text" }
              - { label: "Rating", name: "rating", widget: "number" }